# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shredstream.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'shredstream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import shared_pb2 as shared__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11shredstream.proto\x12\x0bshredstream\x1a\x0cshared.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n\tHeartbeat\x12\x1e\n\x06socket\x18\x01 \x01(\x0b\x32\x0e.shared.Socket\x12\x0f\n\x07regions\x18\x02 \x03(\t\"#\n\x11HeartbeatResponse\x12\x0e\n\x06ttl_ms\x18\x01 \x01(\r\"]\n\nTraceShred\x12\x0e\n\x06region\x18\x01 \x01(\t\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07seq_num\x18\x03 \x01(\r\"\x19\n\x17SubscribeEntriesRequest\"&\n\x05\x45ntry\x12\x0c\n\x04slot\x18\x01 \x01(\x04\x12\x0f\n\x07\x65ntries\x18\x02 \x01(\x0c\x32X\n\x0bShredstream\x12I\n\rSendHeartbeat\x12\x16.shredstream.Heartbeat\x1a\x1e.shredstream.HeartbeatResponse\"\x00\x32\x62\n\x10ShredstreamProxy\x12N\n\x10SubscribeEntries\x12$.shredstream.SubscribeEntriesRequest\x1a\x12.shredstream.Entry0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shredstream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEAT']._serialized_start=81
  _globals['_HEARTBEAT']._serialized_end=141
  _globals['_HEARTBEATRESPONSE']._serialized_start=143
  _globals['_HEARTBEATRESPONSE']._serialized_end=178
  _globals['_TRACESHRED']._serialized_start=180
  _globals['_TRACESHRED']._serialized_end=273
  _globals['_SUBSCRIBEENTRIESREQUEST']._serialized_start=275
  _globals['_SUBSCRIBEENTRIESREQUEST']._serialized_end=300
  _globals['_ENTRY']._serialized_start=302
  _globals['_ENTRY']._serialized_end=340
  _globals['_SHREDSTREAM']._serialized_start=342
  _globals['_SHREDSTREAM']._serialized_end=430
  _globals['_SHREDSTREAMPROXY']._serialized_start=432
  _globals['_SHREDSTREAMPROXY']._serialized_end=530
# @@protoc_insertion_point(module_scope)
