# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import shredstream_pb2 as shredstream__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shredstream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShredstreamStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendHeartbeat = channel.unary_unary(
                '/shredstream.Shredstream/SendHeartbeat',
                request_serializer=shredstream__pb2.Heartbeat.SerializeToString,
                response_deserializer=shredstream__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class ShredstreamServicer:
    """Missing associated documentation comment in .proto file."""

    def SendHeartbeat(self, request, context):
        """RPC endpoint to send heartbeats to keep shreds flowing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShredstreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=shredstream__pb2.Heartbeat.FromString,
                    response_serializer=shredstream__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shredstream.Shredstream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shredstream.Shredstream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Shredstream:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shredstream.Shredstream/SendHeartbeat',
            shredstream__pb2.Heartbeat.SerializeToString,
            shredstream__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ShredstreamProxyStub:
    """Shredstream Proxy

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeEntries = channel.unary_stream(
                '/shredstream.ShredstreamProxy/SubscribeEntries',
                request_serializer=shredstream__pb2.SubscribeEntriesRequest.SerializeToString,
                response_deserializer=shredstream__pb2.Entry.FromString,
                _registered_method=True)


class ShredstreamProxyServicer:
    """Shredstream Proxy

    """

    def SubscribeEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShredstreamProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeEntries': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEntries,
                    request_deserializer=shredstream__pb2.SubscribeEntriesRequest.FromString,
                    response_serializer=shredstream__pb2.Entry.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shredstream.ShredstreamProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shredstream.ShredstreamProxy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShredstreamProxy:
    """Shredstream Proxy

    """

    @staticmethod
    def SubscribeEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shredstream.ShredstreamProxy/SubscribeEntries',
            shredstream__pb2.SubscribeEntriesRequest.SerializeToString,
            shredstream__pb2.Entry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
